### ISSUE TITLE
The output is similar to the input

### ISSUE THREAD

**Issue by Ryuk17** [wangkenpu/Adaptive-Dereverberation-Algorithm#1]
Thanks for your sharing code.  When I run the code, I find the output is similar to the input. 
The spectrum of input is 
![image](https://user-images.githubusercontent.com/22525811/103067718-8aed2200-45f6-11eb-85f2-f49ad9e0ab21.png)
The spectrum output is
![image](https://user-images.githubusercontent.com/22525811/103067740-96d8e400-45f6-11eb-8de7-2c95f9d3c74f.png)

**Comment by Sally-wow** [comment]
> 感谢您的分享代码。运行代码时，我发现输出与输入相似。
> 输入 的频谱为
> ![图像](https://user-images.githubusercontent.com/22525811/103067718-8aed2200-45f6-11eb-85f2-f49ad9e0ab21.png)
> 
> ![图像](https://user-images.githubusercontent.com/22525811/103067740-96d8e400-45f6-11eb-8de7-2c95f9d3c74f.png)



> 感谢您的分享代码。运行代码时，我发现输出与输入相似。
> 输入 的频谱为
> ![图像](https://user-images.githubusercontent.com/22525811/103067718-8aed2200-45f6-11eb-85f2-f49ad9e0ab21.png)
> 
> ![图像](https://user-images.githubusercontent.com/22525811/103067740-96d8e400-45f6-11eb-8de7-2c95f9d3c74f.png)

能加您一个微信吗？我想跟您交流一下关于代码的问题。

**Comment by wangkenpu** [comment]
output 的低频部分共振峰明想更清晰啊！
