### ISSUE TITLE
关于论文的疑问？

### ISSUE THREAD

**Issue by Sally-wow** [wangkenpu/Adaptive-Dereverberation-Algorithm#2]
您写了论文吗？在哪里可以下载？谢谢。

**Comment by wangkenpu** [comment]
复现的别人的论文，请看readme！

**Comment by Sally-wow** [comment]
> 复现的别人的论文，请看readme！

您是指最后的那一篇参考文献吗？[1] Yoshioka T, Tachibana H, Nakatani T, et al. Adaptive dereverberation of speech signals with speaker-position change detection[C]. 2009 IEEE International Conference on Acoustics, Speech and Signal Processing. IEEE, 2009: 3733-3736.
